# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "505015e6892ff21b6c433b09af1c7038"
name = "Shipdartexpress"
handle = "shipdartexpress-connect"
application_url = "https://fe4e-2401-4900-889e-4b55-8845-9fa7-32ac-d080.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "https://app.shipdartexpress.com/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[auth]
redirect_urls = [
  "https://fe4e-2401-4900-889e-4b55-8845-9fa7-32ac-d080.ngrok-free.app/auth/callback",
  "https://fe4e-2401-4900-889e-4b55-8845-9fa7-32ac-d080.ngrok-free.app/auth/shopify/callback",
  "https://fe4e-2401-4900-889e-4b55-8845-9fa7-32ac-d080.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
