# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "505015e6892ff21b6c433b09af1c7038"
name = "Shipdartexpress"
handle = "shipdartexpress-connect"
application_url = "https://spstore.shipdartexpress.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "https://shopify-app-3zy3.onrender.com/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/orders-create"

[auth]
redirect_urls = [
  "https://spstore.shipdartexpress.com/auth/callback",
  "https://spstore.shipdartexpress.com/auth/shopify/callback",
  "https://spstore.shipdartexpress.com/api/auth/callback"
]

[pos]
embedded = false
